// This file is part of nbind, copyright (C) 2014-2016 BusFaster Ltd.
// Released under the MIT license, see LICENSE.

// TODO: this should be autogenerated with real definitions.
export declare var lib: any;

export interface ModuleSpec {
    type: string;
    name: string;
    path: string;
}

export declare function find(path?: string): ModuleSpec;

export declare function init(path?: string, lib?: any): typeof lib;
