// This file is part of nbind, copyright (C) 2014-2016 BusFaster Ltd.
// Released under the MIT license, see LICENSE.

// makeModulePathList and findCompiledModule are adapted from the npm module
// "bindings" licensed under the MIT license terms in BINDINGS-LICENSE.

interface NodeRequire {
	(name: string): any;
	(name: 'path'): {
		dirname(path: string): string;
		resolve(...paths: string[]): string;
	};
	resolve(name: string): string;
}

declare var require: NodeRequire;

const path = require('path'); // tslint:disable-line:no-var-requires

// TODO: this should be autogenerated with real definitions.
export type CExports = any;

declare var process: {
	cwd: () => string,
	env: { [key: string]: string },
	versions: {
		node: string
	},
	platform: string,
	arch: string
};

export interface ModuleSpec {
	type: string;
	name: string;
	path?: string;
}

export class Binding {
	bind(name: string, proto: { new(...args: any[]): any } ) {
		if(this.lib._nbind_value) { // emcc
			this.lib._nbind_value(name, proto);
		} else if(this.lib.NBind) {
			this.lib.NBind.bind_value(name, proto);
		}
	}

	binary: ModuleSpec;
	lib: CExports;
}

let currentBinding: Binding;

/** Called from asm.js during init to get current module. @ignore internal use. */

export function getLib() {
	return(currentBinding.lib);
}

function rethrow(err: any) {
	if(err) throw(err);
}

/** Make list of possible paths for a single compiled output file name. */

function makeModulePathList(root: string, name: string) {
	return([
		// node-gyp's linked version in the "build" dir
		[ root, 'build', name ],

		// node-waf and gyp_addon (a.k.a node-gyp)
		[ root, 'build', 'Debug', name ],
		[ root, 'build', 'Release', name ],

		// Debug files, for development (legacy behavior, remove for node v0.9)
		[ root, 'out', 'Debug', name ],
		[ root, 'Debug', name ],

		// Release files, but manually compiled (legacy behavior, remove for node v0.9)
		[ root, 'out', 'Release', name ],
		[ root, 'Release', name ],

		// Legacy from node-waf, node <= 0.4.x
		[ root, 'build', 'default', name ],

		[
			root,
			process.env['NODE_BINDINGS_COMPILED_DIR'] || 'compiled',
			process.versions.node,
			process.platform,
			process.arch,
			name
		]
	]);
}

export type FindCallback = (err: any, result?: ModuleSpec) => void;

function findCompiledModule(
	root: string,
	specList: ModuleSpec[],
	callback: FindCallback
) {
	const resolvedList: string[] = [];

	for(let spec of specList) {
		// Check if any possible path contains a loadable module,
		// and store unsuccessful attempts.

		for(let pathParts of makeModulePathList(root, spec.name)) {
			const resolvedPath = path.resolve.apply(path, pathParts);

			try {
				spec.path = require.resolve(resolvedPath);

				// Stop if a module was found.
				callback(null, spec);
				return(spec);
			} catch(err) {
				resolvedList.push(resolvedPath);
			}
		}
	}

	const err = new Error(
		'Could not locate the bindings file. Tried:\n' +
		resolvedList.join('\n')
	);

	(err as any).tries = resolvedList;

	callback(err);
	return(null);
}

export interface FindFunction {
	(basePath?: string, cb?: FindCallback): ModuleSpec;
	(cb?: FindCallback): ModuleSpec;
}

export const find = function find(basePath?: string, cb?: FindCallback) {
	let callback = arguments[arguments.length - 1];
	if(typeof(callback) != 'function') callback = rethrow;

	return(findCompiledModule(
		(basePath != callback && basePath) || process.cwd(), [
			{ name: 'nbind.node', type: 'node' },
			{ name: 'nbind.js',   type: 'emcc' }
		], callback
	));
} as FindFunction;

export type InitCallback = (err: any, result: Binding) => void;

export interface InitFunction {
	(basePath?: string, lib?: any, cb?: InitCallback): CExports;
	(basePath?: string, cb?: InitCallback): CExports;
	(cb?: InitCallback): CExports;
}

export const init = function init(basePath?: string, lib?: any, cb?: InitCallback) {
	let callback = arguments[arguments.length - 1];
	if(typeof(callback) != 'function') callback = rethrow;

	const binary = find(basePath != callback && basePath, callback);
	if(!binary) return(null);

	const binding = new Binding();

	binding.binary = binary;
	binding.lib = (lib != callback && lib) || {};

	if(binary.type == 'emcc') {
		initAsm(binding, callback);
	} else {
		initNode(binding, callback);
	}

	return(binding);
} as InitFunction;

function initAsm(binding: Binding, callback: InitCallback) {
	const lib = binding.lib;

	lib.locateFile = lib.locateFile || function(name: string) {
		return(path.resolve(path.dirname(binding.binary.path), name));
	};

	const runtimeInitialized = lib.onRuntimeInitialized;

	lib.onRuntimeInitialized = function() {
		if(runtimeInitialized) runtimeInitialized.apply(this, arguments);
		lib.ccall('nbind_init');
		callback(null, binding);
	};

	currentBinding = binding;

	// Load the Asm.js module.
	require(binding.binary.path);
}

function initNode(binding: Binding, callback: InitCallback) {
	// Load the compiled addon.
	const lib = require(binding.binary.path);

	if(!lib || typeof(lib) != 'object') {
		throw(new Error('Error loading addon'));
	}

	Object.keys(lib).forEach(function(key: string) {
		binding.lib[key] = lib[key];
	});
}
